version: "3.3"
services: 
    
    db:
        image: mysql
        container_name: mysql
        hostname: mysql
        ports:
            - "3306:3306"
        networks: 
            - private_network
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: firefly
            MYSQL_PASSWORD: firefly
            MYSQL_DATABASE: firefly
        volumes:
            - mysql_data_volume:/var/lib/mysql
        # restart: always

    app:
        image: firefly
        container_name: firefly
        hostname: firefly
        ports:
            - "80:8080"
        networks:
            - private_network
        # env_file: env
        environment:
            APP_KEY: mVABGIyA5ASAWL1IViWprQN4Xe7wJ02R
            DB_HOST: mysql 
            DB_PORT: 3306
            DB_CONNECTION: mysql
            DB_DATABASE: firefly
            DB_USERNAME: firefly
            DB_PASSWORD: firefly
        volumes:
            - firefly_export_volume:/var/www/html/storage/export
            - firefly_upload_volume:/var/www/html/storage/upload
        depends_on:
            - db
        # restart: always

networks:
    private_network:
        external: true
        name: private
        
volumes:
    mysql_data_volume:
        external: true
        name: mysql_data
    firefly_export_volume:
        external: true
        name: firefly_export
    firefly_upload_volume:
        external: true
        name: firefly_upload

# docker run \
# --rm \
# --network private \
# -v firefly_export:/var/www/html/storage/export \
# -v firefly_upload:/var/www/html/storage/upload \
# -p 80:8080 \
# -e APP_KEY=mVABGIyA5ASAWL1IViWprQN4Xe7wJ02R \
# -e DB_HOST=mysqlhost \
# -e DB_PORT=3306 \
# -e DB_CONNECTION=mysql \
# -e DB_DATABASE=firefly \
# -e DB_USERNAME=firefly \
# -e DB_PASSWORD=firefly \
# firefly